output-format = "full"
target-version = "py310"
fix = true

[lint]
ignore = [
    "E501",  # Line too long
]

select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "PT", # flake8-pytest-style
    "W",  # pycodestyle warnings
]
