language: python
python:
  - 3.7
  - 3.7-dev
dist: xenial

cache: pip

before_install:
    - pip install docutils
script:
    - make -j

deploy:
    provider: script
    script: bash deploy.bash
    skip_cleanup: true
    on:
        branch: master
