name: Sphinx Build

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy-to-pages:
    name: Build & deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: ðŸ Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          cache: "pip"

      - name: ðŸ‘·â€ Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade -r requirements.txt

      - name: ðŸ”§ Build PEPs
        run: make pages -j$(nproc)

        # remove the .doctrees folder when building for deployment as it takes two thirds of disk space
      - name: ðŸ”¥ Clean up files
        run: rm -r build/.doctrees/

      - name: ðŸš€ Deploy to GitHub pages
        # This allows CI to build branches for testing
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch to deploy to.
          folder: build # Synchronise with build.py -> build_directory
          single-commit: true # Delete existing files
